# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/akshay/graphics/ass2/3D-Game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/akshay/graphics/ass2/3D-Game/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/akshay/graphics/ass2/3D-Game/src/CMakeFiles /home/akshay/graphics/ass2/3D-Game/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/akshay/graphics/ass2/3D-Game/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graphics_asgn1

# Build rule for target.
graphics_asgn1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphics_asgn1
.PHONY : graphics_asgn1

# fast build rule for target.
graphics_asgn1/fast:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/build
.PHONY : graphics_asgn1/fast

arrow.o: arrow.cpp.o

.PHONY : arrow.o

# target to build an object file
arrow.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/arrow.cpp.o
.PHONY : arrow.cpp.o

arrow.i: arrow.cpp.i

.PHONY : arrow.i

# target to preprocess a source file
arrow.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/arrow.cpp.i
.PHONY : arrow.cpp.i

arrow.s: arrow.cpp.s

.PHONY : arrow.s

# target to generate assembly for a file
arrow.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/arrow.cpp.s
.PHONY : arrow.cpp.s

bomb.o: bomb.cpp.o

.PHONY : bomb.o

# target to build an object file
bomb.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/bomb.cpp.o
.PHONY : bomb.cpp.o

bomb.i: bomb.cpp.i

.PHONY : bomb.i

# target to preprocess a source file
bomb.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/bomb.cpp.i
.PHONY : bomb.cpp.i

bomb.s: bomb.cpp.s

.PHONY : bomb.s

# target to generate assembly for a file
bomb.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/bomb.cpp.s
.PHONY : bomb.cpp.s

boundary.o: boundary.cpp.o

.PHONY : boundary.o

# target to build an object file
boundary.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/boundary.cpp.o
.PHONY : boundary.cpp.o

boundary.i: boundary.cpp.i

.PHONY : boundary.i

# target to preprocess a source file
boundary.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/boundary.cpp.i
.PHONY : boundary.cpp.i

boundary.s: boundary.cpp.s

.PHONY : boundary.s

# target to generate assembly for a file
boundary.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/boundary.cpp.s
.PHONY : boundary.cpp.s

cannon.o: cannon.cpp.o

.PHONY : cannon.o

# target to build an object file
cannon.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/cannon.cpp.o
.PHONY : cannon.cpp.o

cannon.i: cannon.cpp.i

.PHONY : cannon.i

# target to preprocess a source file
cannon.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/cannon.cpp.i
.PHONY : cannon.cpp.i

cannon.s: cannon.cpp.s

.PHONY : cannon.s

# target to generate assembly for a file
cannon.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/cannon.cpp.s
.PHONY : cannon.cpp.s

cannonballs.o: cannonballs.cpp.o

.PHONY : cannonballs.o

# target to build an object file
cannonballs.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/cannonballs.cpp.o
.PHONY : cannonballs.cpp.o

cannonballs.i: cannonballs.cpp.i

.PHONY : cannonballs.i

# target to preprocess a source file
cannonballs.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/cannonballs.cpp.i
.PHONY : cannonballs.cpp.i

cannonballs.s: cannonballs.cpp.s

.PHONY : cannonballs.s

# target to generate assembly for a file
cannonballs.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/cannonballs.cpp.s
.PHONY : cannonballs.cpp.s

checkpoint.o: checkpoint.cpp.o

.PHONY : checkpoint.o

# target to build an object file
checkpoint.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/checkpoint.cpp.o
.PHONY : checkpoint.cpp.o

checkpoint.i: checkpoint.cpp.i

.PHONY : checkpoint.i

# target to preprocess a source file
checkpoint.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/checkpoint.cpp.i
.PHONY : checkpoint.cpp.i

checkpoint.s: checkpoint.cpp.s

.PHONY : checkpoint.s

# target to generate assembly for a file
checkpoint.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/checkpoint.cpp.s
.PHONY : checkpoint.cpp.s

color.o: color.cpp.o

.PHONY : color.o

# target to build an object file
color.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/color.cpp.o
.PHONY : color.cpp.o

color.i: color.cpp.i

.PHONY : color.i

# target to preprocess a source file
color.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/color.cpp.i
.PHONY : color.cpp.i

color.s: color.cpp.s

.PHONY : color.s

# target to generate assembly for a file
color.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/color.cpp.s
.PHONY : color.cpp.s

compass.o: compass.cpp.o

.PHONY : compass.o

# target to build an object file
compass.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/compass.cpp.o
.PHONY : compass.cpp.o

compass.i: compass.cpp.i

.PHONY : compass.i

# target to preprocess a source file
compass.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/compass.cpp.i
.PHONY : compass.cpp.i

compass.s: compass.cpp.s

.PHONY : compass.s

# target to generate assembly for a file
compass.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/compass.cpp.s
.PHONY : compass.cpp.s

fuel.o: fuel.cpp.o

.PHONY : fuel.o

# target to build an object file
fuel.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/fuel.cpp.o
.PHONY : fuel.cpp.o

fuel.i: fuel.cpp.i

.PHONY : fuel.i

# target to preprocess a source file
fuel.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/fuel.cpp.i
.PHONY : fuel.cpp.i

fuel.s: fuel.cpp.s

.PHONY : fuel.s

# target to generate assembly for a file
fuel.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/fuel.cpp.s
.PHONY : fuel.cpp.s

fuelmeter.o: fuelmeter.cpp.o

.PHONY : fuelmeter.o

# target to build an object file
fuelmeter.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/fuelmeter.cpp.o
.PHONY : fuelmeter.cpp.o

fuelmeter.i: fuelmeter.cpp.i

.PHONY : fuelmeter.i

# target to preprocess a source file
fuelmeter.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/fuelmeter.cpp.i
.PHONY : fuelmeter.cpp.i

fuelmeter.s: fuelmeter.cpp.s

.PHONY : fuelmeter.s

# target to generate assembly for a file
fuelmeter.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/fuelmeter.cpp.s
.PHONY : fuelmeter.cpp.s

input.o: input.cpp.o

.PHONY : input.o

# target to build an object file
input.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/input.cpp.o
.PHONY : input.cpp.o

input.i: input.cpp.i

.PHONY : input.i

# target to preprocess a source file
input.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/input.cpp.i
.PHONY : input.cpp.i

input.s: input.cpp.s

.PHONY : input.s

# target to generate assembly for a file
input.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/input.cpp.s
.PHONY : input.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/main.cpp.s
.PHONY : main.cpp.s

missile.o: missile.cpp.o

.PHONY : missile.o

# target to build an object file
missile.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/missile.cpp.o
.PHONY : missile.cpp.o

missile.i: missile.cpp.i

.PHONY : missile.i

# target to preprocess a source file
missile.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/missile.cpp.i
.PHONY : missile.cpp.i

missile.s: missile.cpp.s

.PHONY : missile.s

# target to generate assembly for a file
missile.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/missile.cpp.s
.PHONY : missile.cpp.s

needle.o: needle.cpp.o

.PHONY : needle.o

# target to build an object file
needle.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/needle.cpp.o
.PHONY : needle.cpp.o

needle.i: needle.cpp.i

.PHONY : needle.i

# target to preprocess a source file
needle.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/needle.cpp.i
.PHONY : needle.cpp.i

needle.s: needle.cpp.s

.PHONY : needle.s

# target to generate assembly for a file
needle.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/needle.cpp.s
.PHONY : needle.cpp.s

nonedit.o: nonedit.cpp.o

.PHONY : nonedit.o

# target to build an object file
nonedit.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/nonedit.cpp.o
.PHONY : nonedit.cpp.o

nonedit.i: nonedit.cpp.i

.PHONY : nonedit.i

# target to preprocess a source file
nonedit.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/nonedit.cpp.i
.PHONY : nonedit.cpp.i

nonedit.s: nonedit.cpp.s

.PHONY : nonedit.s

# target to generate assembly for a file
nonedit.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/nonedit.cpp.s
.PHONY : nonedit.cpp.s

other_handlers.o: other_handlers.cpp.o

.PHONY : other_handlers.o

# target to build an object file
other_handlers.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/other_handlers.cpp.o
.PHONY : other_handlers.cpp.o

other_handlers.i: other_handlers.cpp.i

.PHONY : other_handlers.i

# target to preprocess a source file
other_handlers.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/other_handlers.cpp.i
.PHONY : other_handlers.cpp.i

other_handlers.s: other_handlers.cpp.s

.PHONY : other_handlers.s

# target to generate assembly for a file
other_handlers.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/other_handlers.cpp.s
.PHONY : other_handlers.cpp.s

parachute.o: parachute.cpp.o

.PHONY : parachute.o

# target to build an object file
parachute.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/parachute.cpp.o
.PHONY : parachute.cpp.o

parachute.i: parachute.cpp.i

.PHONY : parachute.i

# target to preprocess a source file
parachute.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/parachute.cpp.i
.PHONY : parachute.cpp.i

parachute.s: parachute.cpp.s

.PHONY : parachute.s

# target to generate assembly for a file
parachute.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/parachute.cpp.s
.PHONY : parachute.cpp.s

plane.o: plane.cpp.o

.PHONY : plane.o

# target to build an object file
plane.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/plane.cpp.o
.PHONY : plane.cpp.o

plane.i: plane.cpp.i

.PHONY : plane.i

# target to preprocess a source file
plane.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/plane.cpp.i
.PHONY : plane.cpp.i

plane.s: plane.cpp.s

.PHONY : plane.s

# target to generate assembly for a file
plane.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/plane.cpp.s
.PHONY : plane.cpp.s

score.o: score.cpp.o

.PHONY : score.o

# target to build an object file
score.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/score.cpp.o
.PHONY : score.cpp.o

score.i: score.cpp.i

.PHONY : score.i

# target to preprocess a source file
score.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/score.cpp.i
.PHONY : score.cpp.i

score.s: score.cpp.s

.PHONY : score.s

# target to generate assembly for a file
score.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/score.cpp.s
.PHONY : score.cpp.s

sea.o: sea.cpp.o

.PHONY : sea.o

# target to build an object file
sea.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/sea.cpp.o
.PHONY : sea.cpp.o

sea.i: sea.cpp.i

.PHONY : sea.i

# target to preprocess a source file
sea.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/sea.cpp.i
.PHONY : sea.cpp.i

sea.s: sea.cpp.s

.PHONY : sea.s

# target to generate assembly for a file
sea.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/sea.cpp.s
.PHONY : sea.cpp.s

smoke.o: smoke.cpp.o

.PHONY : smoke.o

# target to build an object file
smoke.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/smoke.cpp.o
.PHONY : smoke.cpp.o

smoke.i: smoke.cpp.i

.PHONY : smoke.i

# target to preprocess a source file
smoke.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/smoke.cpp.i
.PHONY : smoke.cpp.i

smoke.s: smoke.cpp.s

.PHONY : smoke.s

# target to generate assembly for a file
smoke.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/smoke.cpp.s
.PHONY : smoke.cpp.s

speedometer.o: speedometer.cpp.o

.PHONY : speedometer.o

# target to build an object file
speedometer.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/speedometer.cpp.o
.PHONY : speedometer.cpp.o

speedometer.i: speedometer.cpp.i

.PHONY : speedometer.i

# target to preprocess a source file
speedometer.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/speedometer.cpp.i
.PHONY : speedometer.cpp.i

speedometer.s: speedometer.cpp.s

.PHONY : speedometer.s

# target to generate assembly for a file
speedometer.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/speedometer.cpp.s
.PHONY : speedometer.cpp.s

timer.o: timer.cpp.o

.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i

.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s

.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/timer.cpp.s
.PHONY : timer.cpp.s

volcano.o: volcano.cpp.o

.PHONY : volcano.o

# target to build an object file
volcano.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/volcano.cpp.o
.PHONY : volcano.cpp.o

volcano.i: volcano.cpp.i

.PHONY : volcano.i

# target to preprocess a source file
volcano.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/volcano.cpp.i
.PHONY : volcano.cpp.i

volcano.s: volcano.cpp.s

.PHONY : volcano.s

# target to generate assembly for a file
volcano.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/volcano.cpp.s
.PHONY : volcano.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... graphics_asgn1"
	@echo "... edit_cache"
	@echo "... arrow.o"
	@echo "... arrow.i"
	@echo "... arrow.s"
	@echo "... bomb.o"
	@echo "... bomb.i"
	@echo "... bomb.s"
	@echo "... boundary.o"
	@echo "... boundary.i"
	@echo "... boundary.s"
	@echo "... cannon.o"
	@echo "... cannon.i"
	@echo "... cannon.s"
	@echo "... cannonballs.o"
	@echo "... cannonballs.i"
	@echo "... cannonballs.s"
	@echo "... checkpoint.o"
	@echo "... checkpoint.i"
	@echo "... checkpoint.s"
	@echo "... color.o"
	@echo "... color.i"
	@echo "... color.s"
	@echo "... compass.o"
	@echo "... compass.i"
	@echo "... compass.s"
	@echo "... fuel.o"
	@echo "... fuel.i"
	@echo "... fuel.s"
	@echo "... fuelmeter.o"
	@echo "... fuelmeter.i"
	@echo "... fuelmeter.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... missile.o"
	@echo "... missile.i"
	@echo "... missile.s"
	@echo "... needle.o"
	@echo "... needle.i"
	@echo "... needle.s"
	@echo "... nonedit.o"
	@echo "... nonedit.i"
	@echo "... nonedit.s"
	@echo "... other_handlers.o"
	@echo "... other_handlers.i"
	@echo "... other_handlers.s"
	@echo "... parachute.o"
	@echo "... parachute.i"
	@echo "... parachute.s"
	@echo "... plane.o"
	@echo "... plane.i"
	@echo "... plane.s"
	@echo "... score.o"
	@echo "... score.i"
	@echo "... score.s"
	@echo "... sea.o"
	@echo "... sea.i"
	@echo "... sea.s"
	@echo "... smoke.o"
	@echo "... smoke.i"
	@echo "... smoke.s"
	@echo "... speedometer.o"
	@echo "... speedometer.i"
	@echo "... speedometer.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
	@echo "... volcano.o"
	@echo "... volcano.i"
	@echo "... volcano.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

